# Generated by Django 4.1.7 on 2023-04-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_last_name', models.TextField()),
                ('doctor_first_name', models.TextField()),
                ('doctor_patronymic', models.TextField(blank=True, null=True)),
                ('doctor_fee', models.TextField()),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('nurse_last_name', models.TextField()),
                ('nurse_first_name', models.TextField()),
                ('nurse_patronymic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nurses',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_snils', models.TextField(unique=True)),
                ('patient_last_name', models.TextField()),
                ('patient_first_name', models.TextField()),
                ('patient_patronymic', models.TextField(blank=True, null=True)),
                ('patient_gender', models.TextField()),
                ('patient_date_of_birth', models.TextField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_date', models.TextField()),
                ('height', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('body_temperature', models.TextField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj_maths.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj_maths.patients')),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj_maths.specialties'),
        ),
        migrations.CreateModel(
            name='NursesMeasurements',
            fields=[
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proj_maths.nurses')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj_maths.measurements')),
            ],
            options={
                'db_table': 'nurses_measurements',
            },
        ),
    ]
